index/urls.py
from django.conf.urls import url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    url(r'^account/$', views.account, name='account'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^investments/$', views.investments, name='investments'),
    url(r'^newlog/$', views.Createcapitallog.as_view(), name='createnewlog'),
    url(r'^newaccount/$', views.CapitalFlow.as_view(), name='capitalflow'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^forgetpass/$', views.forgetpassword, name='forgetpass'),
    url(r'^getacclogs/(?P<pk>[0-9]+)/$', views.AccountLog.as_view(), name='accountlog'),
    url(r'^$', views.index, name='index'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

jimacc/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('index.urls')),
]

index/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
	role = models.CharField(max_length=10, default='read')

	def __str__(self):
		return self.username


class Investment(models.Model):
	investor = models.ForeignKey(User, on_delete=models.CASCADE)
	interest_rate = models.IntegerField()
	amount = models.IntegerField()
	investmentDate = models.DateTimeField()

class Capitallog(models.Model):
	title = models.CharField(max_length=1000)


class Account(models.Model):
	log = models.ForeignKey(Capitallog, on_delete=models.CASCADE)
	amount = models.IntegerField()
	accType = models.CharField(max_length=10)
	description = models.CharField(max_length=1000)

	author = models.ForeignKey(User, on_delete=models.CASCADE)

index/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<nav class="navbar">
		<a href="{% url 'account' %}"><span class="logo">Jim Account</span></a>
		{% if request.user.is_authenticated %}
			<span id="full">
				<a href="{% url 'logout' %}" class="loginA">Logout</a>
				<a href="{% url 'profile' %}" class="loginA">Profile</a>
				<a href="{% url 'investments' %}" class="loginA">Investments</a>
				<a href="{% url 'account' %}" class="loginA">Accounts</a>
			</span>

			<span class="dropcontent" id="half">
				<img src="{% static 'img/but.png' %}" class="dropimg">

				<div class="hide" id="data">
					<a href="{% url 'logout' %}" class="navtag">Logout</a>
					<a href="{% url 'profile' %}" class="navtag">Profile</a>
					<a href="{% url 'investments' %}" class="navtag">Investments</a>
					<a href="{% url 'account' %}" class="navtag">Accounts</a>
				</div>
			</span>
		{% endif %}
	</nav>
	
</head>
<body>
	<ul id="messagelist">
		<p id="reactmessage" class="error hide"></p>
		{% if messages %}
			{% for message in messages %}
				<li id="message" {% if message.tags %} class="{{message.tags}}" {% endif %}>
					{{message}}
				</li>
			{% endfor %}
		{% endif %}
	</ul>
	<div class="container">
		{% block content %}

	    {% endblock %}
    </div>
</body>
<script type="text/javascript" src="{% static 'jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'script.js' %}"></script>

<!-- <script type="text/javascript" src="{% static 'index/js/jsapi' %}"></script> -->
 </html>

index/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
	{% verbatim %}
		<template id="newaccountTemplate">
			<h5>{{description}} <span class="right">#{{amount}}</span></h5>
			<span class="accDate">{{accType}}</span>
		</template>
	{% endverbatim %}
	<div class="jump">
		{% if user.role == 'write' %}
			<a href="#" class="btnwhite hider">New Log</a>
			<div class="hide newacc">
				<span class="del hider">X</span>
				<form id="newlogForm">
					<p class="hide" id="newlogToken">{{csrf_token}}</p>
					<input type="text" class="newlogtitle" placeholder="Enter account title">
					<input type="submit" value="Add">
				</form>
			</div>
			<br><br>

			<div class="newcontent">
				<form id="newaccountForm">
					<input type="hidden" name="author" value="{{user.id}}">
					<label class="black">Amount:</label>
					<input type="number" name="amount" required>
					<input type="radio" name="type" value="output"> <span>Output</span>
					<input type="radio" name="type" value="input" checked> <span>Input</span>
					<input type="text" name="description" placeholder="Description" required>

					<input type="submit" value="Submit">
				</form>
			</div>
		{% endif %}
		<div class="account">
			<h2 class="currentlog" id="{{lastlog.id}}">{{lastlog.title}}</h2>
			<div class="spending">
				<h5 class="total">Total Input: #<span id="totinput">{{totinput}}</span>; Total Output: #<span id="totoutput">{{totoutput}}</span></h5><br>
				<div class="acc">
					{% if lastlog.account_set.count %}
						{% for acc in lastlog.account_set.all %}
							<h5>{{acc.description}} <span class="right">#{{acc.amount}}</span> </h5>
							<span class="accDate">{{acc.accType}}</span>
						{% endfor %}
					{% else %}
						<h5 class="noacc">No account yet</h5>
					{% endif %}
				</div>
			</div>
		</div>
	</div>

	<div class="jump">
		<h3>Recent accounts</h3>
		<div class="recents"></div>
		{% if logs.count > 1 %}
			{% for log in logs %}
				{% if not forloop.last %}
					<a href="#" class="recentA" id="account{{log.id}}">{{log.title}}</a>
				{% endif %}
			{% endfor %}
		{% else %}
			<h5 class="norecent">No recent log</h5>
		{% endif %}
	</div>

	<script type="text/javascript" src="{% static 'mustache.js' %}"></script>
{% endblock %}

index/templates/investments.html
{% extends "base.html" %}


{% load static %}

{% block content %}
	{% if user.role == 'write' %}
		<form class="investmentForm" method="post" action="">
			{% csrf_token %}
			<h2>New investment</h2>
			<label>Investor:</label>
			<select name="investor">
				{% for investor in investors %}
					<option value="{{investor.pk}}">{{investor.username}}</option>
				{% endfor %}
			</select>
			<label>Amount:</label>
			<input type="number" name="amount">

			<label>Rate:</label>
			<input type="number" name="interest_rate">

			<label>Investment Date:</label>
			<input type="date" name="investmentDate">

			<input type="submit" value="Add">
		</form>
	{% endif %}
	<div class="fromleft">
		<h2 class="center">Investors({{investors | length}})</h2>
		{% if investors %}
			{% for investor in investors %}
				<div class="infodrop">
					<div>
						<!-- Info that always show -->
						<div class="sm-rol-2">
							<div class="col-6">
								<span class="dropfront">{{investor.username}}</span>
							</div>
						</div>

						<div class="sm-rol-2">
							<div class="col-6">
								<span class="dropfront">{{investor.first_name}} {{investor.last_name}}</span>
							</div>
							<span class="right more" data-drop="{{investor.pk}}">More</span>
						</div>
						<!-- Info that show on click -->
						<div class="hide" id="{{investor.pk}}">
							<br>
							{% if investor.investment_set.count %}
								{% for investment in investor.investment_set.all %}
									<div class="sm-rol-2">
										<div class="col-6">
											<span class="dropfront2">Amount: #{{investment.amount}} X {{investment.interest_rate}}</span>
										</div>
									</div>
									
									<div class="sm-rol-2">
										<div class="col-6">
											<span class="dropfront2">Date: {{investment.investmentDate|date:"d, M, Y"}}</span>
										</div>
									</div>

									<br>
									<br>
								{% endfor %}
							{% else %}
								<h5>{{investor.username}} have no investment yet</h5>
							{% endif %}
						</div>
					</div>
				</div>
			{% endfor %}
		{% else %}
			<h3>There is no investment yet</h3>
		{% endif %}
	</div>
{% endblock %}

index/templates/login.html
{% extends "base.html" %}

{% load static %}

{% block content %}
	<!-- Login form -->
	<div class="login-container innernavactive" data-access="#login">
		<img src="{% static 'img/user.png' %}" class="legend">
		<form action="" method="post">
			{% csrf_token %}
			<h1 class="white">Member Login</h1>
			<div class="login-field">
				<label class="alone">Username </label>
				<input type="text" name="username" placeholder="Enter Username" class="login-input" required>
			</div>

			<div class="login-field">
				<label class="alone">Password </label>
				<input type="password" name="password" placeholder="Enter Password" class="login-input" required>
			</div>

			<div class="login-field">
				<input type="submit" value="Login" class="login-submit">
				<p class="forget">Forget password? <a href="#" class="forgetpass" data-access="#forget">Click here</a></p>

			</div>
		</form>

	</div>

	<!-- Forget password form -->
	<div id="forget" class="login-container hide">
		<img src="{% static 'img/user.png' %}" class="legend">
		<form action="{% url 'forgetpass' %}" method="post">
			{% csrf_token %}
			<h1 class="white">Forget Password</h1>
			<div class="login-field">
				<label class="alone">Username </label>
				<input type="text" name="username" placeholder="Enter Username" class="login-input" required>
				<div class="login-field">
				<input type="submit" value="Reset" class="login-submit">
			</div>
			</div>
		</form>
	</div>
{% endblock %}

index/templates/profile.html
{% extends "base.html" %}

{% load static %}

{% block content %}
	<div class="reg-container">
		<img src="{% static 'img/user.png' %}" class="legend">
		<h1 class="white center">Edit profile</h2>

		<div>
			<form action="" method="post">
				{% csrf_token %}
				<div class="rol-1">
					<div class="sm-rol-2">
						<div class="col-6">
							<label>First name</label>
							<input type="text" name="first_name" value="{{user.first_name}}" placeholder="Enter First name" required>
						</div>
					</div>
					<div class="sm-rol-2">
						<div class="col-6">
							<label>Last name</label>
							<input type="text" name="last_name" value="{{user.last_name}}" placeholder="Enter Last name" required>
						</div>
					</div>
					<div class="sm-rol-2">
						<div class="col-6">
							<label>Email</label>
							<input type="email" name="email" value="{{user.email}}" placeholder="Enter Email" required>
						</div>
					</div>
					<div class="sm-rol-2">
						<div class="col-6">
							<label>Current Password</label>
							<input type="password" name="currentpassword" placeholder="Current Password" required>
						</div>
					</div>
					<h5 class="white center">Change password</h5>
					<div class="sm-rol-2">
						<div class="col-6">
							<label>New Password</label>
							<input type="password" name="newpassword" placeholder="Choose Password">
						</div>
					</div>
					<div class="sm-rol-2">
						<div class="col-6">
							<label>Confirm Password</label>
							<input type="password" name="newpassword2" placeholder="Confirm Password">
						</div>
					</div>
				</div>
				<input type="submit" value="Edit Profile" class="regsubmit">
			</form>
		</div>
	</div>
{% endblock %}

index/templates/register.html
{% extends "base.html" %}

{% load static %}

{% block content %}
	<div class="reg-container">
		<img src="{% static 'img/user.png' %}" class="legend">
		<h1 class="white center">Board Registration</h2>

		<div>
			<form action="" method="post">
				{% csrf_token %}
				<span class="sub-topic">Role</span>
				<div class="paymet">
					<input type="radio" name="role" value="read" checked> <span class="white">Read</span>
					<input type="radio" name="role" value="write"> <span class="white">Write</span>
				</div>
				<br>

				<div class="lg-rol">
					<div class="col-6-lg">
						<label>Username</label>
						<input type="text" name="username" placeholder="Choose Username" required>
					</div>
				</div>
				<div class="rol-1">
					<div class="sm-rol-2">
						<div class="col-6">
							<label>First name</label>
							<input type="text" name="first_name" placeholder="Enter First name" required>
						</div>
					</div>
					<div class="sm-rol-2">
						<div class="col-6">
							<label>Last name</label>
							<input type="text" name="last_name" placeholder="Enter Last name" required>
						</div>
					</div>
					<div class="sm-rol-2">
						<div class="col-6">
							<label>Email</label>
							<input type="email" name="email" placeholder="Enter Email" required>
						</div>
					</div>
					<div class="sm-rol-2">
						<div class="col-6">
							<label>Password</label>
							<input type="password" name="password" placeholder="Choose Password" required>
						</div>
					</div>
					<div class="sm-rol-2">
						<div class="col-6">
							<label>Confirm Password</label>
							<input type="password" name="password2" placeholder="Confirm Password" required>
						</div>
					</div>

					<div class="sm-rol-2">
						<div class="col-6">
							<label>Pin</label>
							<input type="password" name="pincode" placeholder="Enter creation pin" required>
						</div>
					</div>
				</div>
				<input type="submit" value="Register" class="regsubmit">
			</form>
		</div>
	</div>
{% endblock %}